# Generated by Django 5.2 on 2025-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
    ]
